# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  Opengl_config = debug_x64
endif
ifeq ($(config),release_x64)
  Opengl_config = release_x64
endif

PROJECTS := Opengl

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Opengl:
ifneq (,$(Opengl_config))
	@echo "==== Building Opengl ($(Opengl_config)) ===="
	@${MAKE} --no-print-directory -C . -f Opengl.make config=$(Opengl_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Opengl.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Opengl"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"